services:
  api:
    build: .
    ports: ["8000:8000"]
    env_file: .env.docker
    environment:
      APP_ENV: "docker"
    volumes:
      # This is a bind mount, and it has 3 parts separated by :
      # ./app is the source from your machine where the code lives
      # /app/app is the target path, the path in the container where the code will live
      # ro is the mode (read-only)
      - ./app:/flyswatter/app:ro
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16
    env_file: .env.docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  worker:
    build: 
      context: .
      dockerfile: Dockerfile_worker
    env_file: .env.docker
    depends_on:
      - db
      - redis

  minio:
    image: minio/minio
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env.docker
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data

volumes:
  pgdata:
  minio_data:
    driver: local