# 1. Base image: lightweight Python
FROM python:3.12-slim

# 2. Install public root CA certificates
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# 3. Set working directory inside the container
WORKDIR /flyswatter

# 4. Install Poetry (package manager)
RUN pip install --no-cache-dir poetry

# 5. Copy dependency files first (better build caching)
COPY pyproject.toml poetry.lock* ./

# 6. Install dependencies inside container
# Tells poetry to not create a venv since the container is already isolated
# Then it installs your dependencies as declared in pyproject.toml and poetry.lock.
# --no-ansi means no colored output to make logs cleaner in Docker
RUN poetry config virtualenvs.create false \
 && poetry install --no-interaction --no-ansi

# 7. Copy source code (host ./app → container /flyswatter/app)
COPY app ./app

# 8. Define the default startup command
CMD ["celery", "-A", "app.worker.celery_app.app", "worker", "-c", "1", "--loglevel=info", "-Q", "pdfs"]
