services:
  api:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    environment:
      APP_ENV: "docker"
    volumes:
      # This is a bind mount, and it has 3 parts separated by :
      # ./app is the source from your machine where the code lives
      # /app/app is the target path, the path in the container where the code will live
      # ro is the mode (read-only)
      - ./app:/flyswatter/app:ro
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: