"""Added url and dates to artifact

Revision ID: 68f337ef00c9
Revises: 6dce8d020c1e
Create Date: 2025-10-02 12:31:49.963281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f337ef00c9'
down_revision: Union[str, Sequence[str], None] = '6dce8d020c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('url', sa.String(), nullable=False))
    op.add_column('artifacts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('artifacts', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'expires_at')
    op.drop_column('artifacts', 'created_at')
    op.drop_column('artifacts', 'url')
    # ### end Alembic commands ###
